### ISSUE TITLE
Sorry to bother you again

### ISSUE THREAD

**Issue by OlegKostin** [wizered67/ProjectVisualNovel#2]
Hello again, ive learnt libgdx but still can not open yuor project. Please, can u add all those test files? thx!

**Comment by wizered67** [comment]
Go ahead and try again now. I updated some of the loading code to not load the not included assets. Let me know if it still gives you an error and what it is.

**Comment by wizered67** [comment]
My bad, just realized I screwed up with that. About to correct it again.

**Comment by wizered67** [comment]
Okay try again now!

**Comment by OlegKostin** [comment]
its working! Thanks!

**Comment by wizered67** [comment]
Excellent! Keep in mind that I'll still be adding more stuff as time goes on. If you have any problems or find bugs, feel free to add an issue!
